"""增加test_cases

Revision ID: 1d277dee8f95
Revises: c3ba2ec9dc7d
Create Date: 2020-04-29 18:39:00.083850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d277dee8f95'
down_revision = 'c3ba2ec9dc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('case_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    # ### end Alembic commands ###
