"""User增加新字段

Revision ID: 604b88e1a7ae
Revises: eb8f261396b0
Create Date: 2020-04-06 12:15:33.149982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604b88e1a7ae'
down_revision = 'eb8f261396b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_see', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_see')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
