"""增加错误记录表

Revision ID: 90c7b1caca2f
Revises: e184934f65d2
Create Date: 2020-05-13 19:10:05.170095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c7b1caca2f'
down_revision = 'e184934f65d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases_failed_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True, comment='test_cases用例id'),
    sa.Column('test_case_json', sa.JSON(), nullable=True, comment='执行时用例内容'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('test_cases', 'status',
               existing_type=sa.VARCHAR(length=128),
               comment='用例状态',
               existing_comment='用例状态：declare',
               existing_nullable=True)
    op.drop_column('test_cases', 'case_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('case_status', sa.SMALLINT(), autoincrement=False, nullable=True, comment='用例状态'))
    op.alter_column('test_cases', 'status',
               existing_type=sa.VARCHAR(length=128),
               comment='用例状态：declare',
               existing_comment='用例状态',
               existing_nullable=True)
    op.drop_table('test_cases_failed_history')
    # ### end Alembic commands ###
