"""修改外键依赖

Revision ID: c3ba2ec9dc7d
Revises: 9d173e6f0970
Create Date: 2020-04-27 10:23:54.654791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ba2ec9dc7d'
down_revision = '9d173e6f0970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
