"""增加触发器字段

Revision ID: d01352501c55
Revises: 1d277dee8f95
Create Date: 2020-04-30 18:57:39.602254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01352501c55'
down_revision = '1d277dee8f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('trigger', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'trigger')
    # ### end Alembic commands ###
