"""增加创建更新人字段与新的状态字段

Revision ID: e184934f65d2
Revises: d01352501c55
Create Date: 2020-05-11 16:03:59.500778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e184934f65d2'
down_revision = 'd01352501c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('case_status', sa.SmallInteger(), nullable=True, comment='用例状态'))
    op.add_column('test_cases', sa.Column('cteated_id', sa.Integer(), nullable=True, comment='创建者id'))
    op.add_column('test_cases', sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新者id'))
    op.alter_column('test_cases', 'case_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='用例内容',
               existing_nullable=True)
    op.alter_column('test_cases', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment='用例名称',
               existing_nullable=True)
    op.alter_column('test_cases', 'service',
               existing_type=sa.VARCHAR(length=128),
               comment='所属微服务',
               existing_nullable=True)
    op.alter_column('test_cases', 'status',
               existing_type=sa.VARCHAR(length=128),
               comment='用例状态：declare',
               existing_nullable=True)
    op.alter_column('test_cases', 'team',
               existing_type=sa.VARCHAR(length=128),
               comment='开发团队',
               existing_nullable=True)
    op.alter_column('test_cases', 'trigger',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='时间触发器',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_cases', 'trigger',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='时间触发器',
               existing_nullable=True)
    op.alter_column('test_cases', 'team',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='开发团队',
               existing_nullable=True)
    op.alter_column('test_cases', 'status',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='用例状态：declare',
               existing_nullable=True)
    op.alter_column('test_cases', 'service',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='所属微服务',
               existing_nullable=True)
    op.alter_column('test_cases', 'name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='用例名称',
               existing_nullable=True)
    op.alter_column('test_cases', 'case_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='用例内容',
               existing_nullable=True)
    op.drop_column('test_cases', 'updated_id')
    op.drop_column('test_cases', 'cteated_id')
    op.drop_column('test_cases', 'case_status')
    # ### end Alembic commands ###
